### ISSUE TITLE
Confirm Joey Gu interest/ownership

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/docs.openedx.org#141]

**Comment by jmakowski1123** [comment]
Jenna reached out to schedule follow up chat on 9/22.

**Comment by jmakowski1123** [comment]
- [ ] JM follow up

**Comment by feanil** [comment]
@jmakowski1123 any update on this? Should we close for now?

**Comment by sarina** [comment]
Closing this - @jmakowski1123 you can reopen if it's still relevant.
