### ISSUE TITLE
[Developer] How To: Get Ready for Frontend Development

### ISSUE THREAD

**Issue by feanil** [openedx/docs.openedx.org#147]

**Comment by feanil** [comment]
Looking at the existing docs, it looks like most of the frontend apps have specific READMEs that provide instructions on how to get started.  A generic how-to might not be very useful.  @jmakowski1123 what do you think about maybe putting this back on the backlog for a bit.  Since this also relies on devstack which we're trying to stop using as well.

**Comment by jmakowski1123** [comment]
Do you think it's worth having a how-to in the docs index for frontend developers that gives them that instruction specifically? Go to the README of the repo for the frontend you want to work on, etc.
