### ISSUE TITLE
Documentation: How to add a language to the supported list in the current way

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/docs.openedx.org#154]
Write a proper How To on adding a new language to the platform, once [discovery](https://github.com/openedx/tcril-engineering/issues/479) is complete.

Refer to [this guide](https://github.com/openedx/tcril-engineering/issues/479), but also touch base with Feanil, as he's developing an [Open edX specific guide](https://docs.openedx.org/en/latest/documentors/quickstarts/index.html) on how to write How Tos.

**Comment by arbrandes** [comment]
The Atlas migration is in full swing, so we can (finally) close this.
