### ISSUE TITLE
Review Wanda's Quickstart

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/docs.openedx.org#172]

**Comment by jmakowski1123** [comment]
@feanil Here's a WIP draft from a few folks at edunext. They aren't finished yet but wanted some feedback on what they've done so far: https://docs.google.com/document/d/1qopOWpNw8Ya_m8SEisiJdIhQwraoloZgD6TahpTn3vY/edit#

Few thoughts:

1. I went through and noted a few sections that we probably want to pull out of a quick start doc and expand as references. Lmk if you agree or disagree with those sections.
2. I also tried to flag where we'd want to link out to a how-to (and we can get a good list of future how-tos from this doc)
3. The biggest question I'm grappling with - this is quite long for a Quickstart. But I'm having trouble figuring out where/how to shorten it, because it does very accurately go through the end-to-end process of running a course. The steps themselves are succinct...there are just a lot of steps. Do we just accept that the workflow to run a course is more involved, and thus necessitates a longer quick start? Or maybe you have a better sense of how to shorten it without losing critical steps in the flow? Lmk what you think.

**Comment by feanil** [comment]
Looking through the content, there's so much good stuff! But I agree, I think it's too big for a quickstart where we want to have people experience a more simple happy path.  One thought is that we could pull out a much simpler version of this where we don't touch all the settings described(assuming it's possible to do that and have a reasonable course).  Then take this doc and make it into a series of How-Tos for the various settings along with a Reference doc that could be titled.  "Course Lifecycle Checklist" which might walk people through what to think about at the various phases of the course:
- Before Building(Instructional Design)
- While Building (Content, Dates, Beta Testers, other config)
- Publishing the Course
- While the course is running
- Closing the Course
- After the Course is Closed

**Comment by jmakowski1123** [comment]
Closing this ticket as they continue writing and will create a new ticket once they are ready for full integration and review.
