### ISSUE TITLE
A Simple Opinionated Intro to RST exists (make it or link to an existing one)

### ISSUE THREAD

**Issue by feanil** [openedx/docs.openedx.org#18]

**Comment by jmakowski1123** [comment]
Aggregated comments around RST as the choice authoring tool:

- I think this is a good move, and agree it can help with organization. Please consider and document search as part of discovery. I'd like us to expose and invest in https://docs.edx.org/search, or find an alternative. Note that RTD search is limited to the current book.	

- It's great to have a single point where you can go, and there find you way around. I wonder if RTD is the best tool, or if there are better tools. Sphinx can be cumbersome for non-tech users. What about Gitbook?	

- Have you tried [Gitbook](https://gitbook.com/)? It has the power of git but a more friendly interface than rst.

- Even as a developer, I find it hard to author in RST. But to your point, it’s less about writing the words and more about the structure and discoverability of those words. Even with that though, someone has to be able to understand where those new words will link to RTD and how to link them. If a contributor doesn’t want/know how to do that themselves, there should be a clear process to request that sort of linking, or transfer from their doc scheme of choice to RTD.

**Comment by jmakowski1123** [comment]
Related PR: https://github.com/openedx/docs.openedx.org/pull/20

**Comment by feanil** [comment]
This page now exists so I think we can call this task done.  https://new-open-edx-docs-site.readthedocs.io/en/latest/creating_doc/quickstart_rst.html

**Comment by feanil** [comment]
Actually, I'm gonna re-open this, we have not had someone try it out yet so there may be more updates to it before we close this.
