### ISSUE TITLE
sphinx-panels is no longer maintained move to sphinx-design for panels and cards

### ISSUE THREAD

**Issue by feanil** [openedx/docs.openedx.org#238]
Currently [docs.openedx.org](https://github.com/openedx/docs.openedx.org/blob/main/source/conf.py#L38) uses the [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/) extension to show the panels on various pages.  Update it to use [cards from sphinx-design](https://sphinx-design.readthedocs.io/en/furo-theme/cards.html)

You'll have to:
* Update [base.in](https://github.com/openedx/docs.openedx.org/blob/main/requirements/base.in#L8) to swap out the dependencies.
* Update [conf.py](https://github.com/openedx/docs.openedx.org/blob/main/source/conf.py#L38) to use the new extension instead of the old one.
* Make sure the build runs clean and looks okay with the new panels.

**Comment by brian-smith-tcril** [comment]
noticed a few things while poking around in here
![image](https://user-images.githubusercontent.com/112954497/220714463-e0391bc4-a52b-4bf9-83a4-32ecb8b88517.png)
 vs 
![image](https://user-images.githubusercontent.com/112954497/220714486-e149f172-81a0-4f18-baac-623dd3ed5d1d.png)

for consistency, which should we use?

also the spacing for the bulleted lists on the homepage (using toctree) is different than the spacing on the role pages
![image](https://user-images.githubusercontent.com/112954497/220714718-ce632125-4f3b-4054-868a-a32d31cb268b.png)
vs
![image](https://user-images.githubusercontent.com/112954497/220714773-d61f8bb9-4c48-4b35-97da-8b034ba3d212.png)

i could look into trying to get those lined up while i'm in here, just not sure if we want to keep this PR more focused or if we're ok with adding a few bonus things

**Comment by feanil** [comment]
I would say keep this PR more focused, and let's use `Documentors` since it's a bit more succinct.
