### ISSUE TITLE
Clean up heading symbols in release notes

### ISSUE THREAD

**Issue by kdmccormick** [openedx/docs.openedx.org#307]
### Background

We have been moving things from the old docs site (openedx/edx-documentation, hosted at https://edx.readthedocs.io) to the new docs site (this repo, hosted at https://docs.openedx.org).

The [release notes](https://docs.openedx.org/en/latest/community/release_notes/index.html) were copied in from the old docs repo, but the headings haven't been updated to use the `#/*/=/-` (4/3/2/1) system [described here](https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html#headings).

The release notes do render fine currently. However, we're trying to move to those consistent heading symbols so that it'll be simpler to write docs and easier to compose & copy-paste rST documentation across the new docs site.

### Acceptance Criteria

Go through every file under https://github.com/openedx/docs.openedx.org/tree/main/source/community/release_notes. 

Ensure the following format is used:

```rst
Heading 1
#########

...

Heading 2
*********

...

Heading 3
=========

...

Heading 4
---------

...
```

This shouldn't cause any visual changes to the docs.

**Comment by feanil** [comment]
FYI, I've used the following script to do this kind of thing in the past:
```
"""
Fileniput just looks at sys.argv[1:] and processes all the file names provided.

In zsh you can run this on all RST files by running something like

``python rerule.py ~/path/to/dir/**/*.rst``

This will find all rst files under ``dir`` and process them.

It will treat overlines differently from the same char as an underline
but it will drop the overline in the output.
"""


import fileinput
import re
import sys

# The order we want our heading rules.
GOOD_RULES = "#*=-~."

# Swap overlines with weird punctuation so that
# we don't confuse them with underlines and can drop
# them more easily.

OVERLINE_MAPPINGS = {
    "#": "\u2051",
    "*": "\u2053",
    "=": "\u0fd4",
    "-": "\u1aad",
    "~": "\u1c7f",
    ".": "\ua60f",
}
# A rule is any line of all the same non-word character, 3 or more.
RULE_RX = r"^([^\w\d])\1\1+$"

had_overline = False

for line in fileinput.input(inplace=True):
    if fileinput.isfirstline():
        rules = {}
    line = line.rstrip()

    if fileinput.isfirstline() and re.search(RULE_RX, line):
        # First line is an overline heading.
        had_overline = True
        continue

    if re.search(RULE_RX, line) and had_overline:
        # Treat this char as a different one.
        # BUG: We're not making sure that the previous overline was the same
        # character as this underline.  This might cause an issue but seems
        # fine for now.
        line = OVERLINE_MAPPINGS[line[0]] * len(line)
        had_overline = False

    if re.search(RULE_RX, line):
        if line[0] not in rules:
            rules[line[0]] = GOOD_RULES[len(rules)]
        line = rules[line[0]] * len(line)
    print(line)
```
