### ISSUE TITLE
add new discussion forum events to tracking log event list

### ISSUE THREAD

**Issue by pdpinch** [openedx/docs.openedx.org#342]
These following events should be added to the tracking log event list: 

- `edx.forum.response.mark`
- `edx.forum.response.unmark`

(added in by https://github.com/openedx/edx-platform/pull/31378)

- `edx.forum.thread.reported`
- `edx.forum.response.reported`
- `edx.forum.comment.reported`
- `edx.forum.thread.unreported`
- `edx.forum.response.unreported`
- `edx.forum.comment.unreported`

(added by https://github.com/openedx/edx-platform/pull/31214)

>               I wasn't aware of them, but I was speaking with @ayub02 about the existing events being maintained (they are). He might know more about the new events. We should document them here, too: https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_log_event_list.html

_Originally posted by @bmtcril in https://github.com/openedx/docs.openedx.org/pull/321#discussion_r1229745229_

**Comment by bmtcril** [comment]
Thanks @pdpinch I'll take care of this
