### ISSUE TITLE
Dev Guide Section 3.1 Process for Contributing Code

### ISSUE THREAD

**Issue by sarina** [openedx/docs.openedx.org#399]
- [ ] Review/edit existing words
- [ ] Fill out the Roles section

https://docs.openedx.org/en/latest/developers/references/legacy_guide/process/overview.html

**Comment by sarina** [comment]
Addressed by https://github.com/openedx/docs.openedx.org/pull/395/files

**Comment by MaferMazu** [comment]
@sarina, can we close this? You already addressed it.

**Comment by sarina** [comment]
thanks!
