### ISSUE TITLE
Document maintainer's obligations

### ISSUE THREAD

**Issue by arbrandes** [openedx/docs.openedx.org#475]
* Include a link to https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3883302913/The+Open+edX+Product+Review+Process
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/docs.openedx.org/pull/476
```

**Comment by sarina** [comment]
@arbrandes - add to https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html and/or https://docs.openedx.org/en/latest/developers/how-tos/ongoing-maintainers-tasks.html :)
