### ISSUE TITLE
Add Unmaintained warning to Ecomm Docs

### ISSUE THREAD

**Issue by sarina** [openedx/docs.openedx.org#525]
The README on https://github.com/openedx/ecommerce indicates it is deprecated, but no docs do, leading to end-user confusion.

This ticket is to add DEPR warnings to ecommerce _documentation_, since most people go to the docs rather than the repos.

Note that in the [TOC meeting notes from June 2024](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4339204098/TOC+Meeting+Notes+-+2024-06-11) they clearly say that the e-commerce service is deprecated.

Ryan reports:

This documentation was where I went first to find info about ecommerce: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/index.html

Then based on the Tutor distribution documentation:

* https://edly.io/tutor/ecommerce-plugin/
* https://github.com/overhangio/tutor-ecommerce

Those were probably the three main information sources that led me to believe the ecommerce plugin was still viable.

**Comment by sarina** [comment]
cc @RyanRad-BSG as reporter of this issue

**Comment by MaferMazu** [comment]
The ecommerce service is still viable, but its current status is under-maintained and is in the process of being deprecated. Kyle updated the info of the openedx/ecommerce repository with that info. Should we try adding via a PR that warns in Edly, Overhangio, and edX doc repositories?

cc @sarina @RyanRad-BSG

**Comment by sarina** [comment]
I changed the title to "Unmaintained". Most end-users are reading the documentation, not the repo's readme. Warnings like that on the ecommerce repo should go in any place that people may be looking for information on ecommerce.

**Comment by sarina** [comment]
in the [TOC meeting notes from June 2024](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4339204098/TOC+Meeting+Notes+-+2024-06-11) it clearly says the e-commerce service is deprecated.

**Comment by sarina** [comment]
I made PRs to the docs site and the Tutor ecomm plugin; I reached out to edly about updating the tutor plugin page at https://edly.io/tutor/ecommerce-plugin/

**Comment by regisb** [comment]
Sorry about my delayed response. The ecommerce plugin page has been updated: https://edly.io/tutor/ecommerce-plugin/

**Comment by sarina** [comment]
Thanks @regisb !
