### ISSUE TITLE
Add a license to this repo

### ISSUE THREAD

**Issue by feanil** [openedx/docs.openedx.org#72]
Figure out the correct license for this repo and add it.

Creative commons might make sense since it's mostly text content and not code.  Talk to tCRIL legal before deciding.

**Comment by e0d** [comment]
@feanil realized that I don't know what "this repo" refers to, is it tcril-engineering?

**Comment by feanil** [comment]
This is an issue on the docs.openedx.org repo so that's what I was referring to.  And yea, you did this a while ago so it can close.
